import { SplitCodeExample } from '@/components/split-code-example'

const skirCode = `// shapes.skir

struct Shape {
  points: [Point];
  /// A short string describing this shape.
  label: string;
}

struct Point {
  x: int32;
  y: int32;
  label: string;
}

method IsConvex(
  Shape
): bool = 412938;`

const codeExamples = {
  typescript: `import { ServiceClient } from "skir-client";
// Import from file generated by Skir
import { IsConvex, Shape } from "../skirout/shapes.js";

// Construct an immutable Shape
const triangle = Shape.create({
  points: [
    { x: 0, y: 0, label: "A" },
    { x: 10, y: 0, label: "B" },
    { x: 0, y: 10, label: "C" },
  ],
  label: "ABC",
});

// Demonstrate round-trip serialization
const restored = Shape.serializer.fromJson(
  Shape.serializer.toJson(triangle)
);

console.log(restored.label);  // ABC

// Send RPC
const isConvex = await new ServiceClient(
  "http://localhost:8080/api"
).invokeRemote(IsConvex, triangle);

console.log(isConvex);  // true`,

  python: `# Import from module generated by Skir
from skirout.shapes_skir import IsConvex, Point, Shape
import skir

# Construct an immutable Shape
triangle = Shape(
    points=(
        Point(x=0, y=0, label="A"),
        Point(x=10, y=0, label="B"),
        Point(x=0, y=10, label="C"),
    ),
    label="ABC",
)

# Demonstrate round-trip serialization
restored = Shape.serializer.from_json_code(
    Shape.serializer.to_json_code(triangle),
)
print(restored.label)  # ABC

# Send RPC
is_convex = skir.ServiceClient(
  "http://localhost:8080/api",
).invoke_remote(
    IsConvex,
    triangle,
)
print(is_convex)  # true`,

  cpp: `#include "httplib.h"
#include "skir.h"
// Import from header generated by Skir
#include "skirout/shapes.h"

using ::skirout_shapes::IsConvex;
using ::skirout_shapes::Point;
using ::skirout_shapes::Shape;

// Construct an immutable Shape
const Shape triangle = Shape::whole{
    .label = "ABC",
    .points = {
        Point::whole{.label = "A", .x = 0, .y = 0},
        Point::whole{.label = "B", .x = 10, .y = 0},
        Point::whole{.label = "C", .x = 0, .y = 10},
    },
};

// Demonstrate round-trip serialization
const absl::StatusOr<Shape> restored =
    skir::Parse<Shape>(skir::ToDenseJson(triangle));
std::cout << restored->label << "\\n";  // ABC

// Send RPC
std::unique_ptr<skir::service::Client> client =
    skir::service::MakeHttplibClient(
        std::make_unique<httplib::Client>(
            "localhost",
            8080,
        ),
        "/api",
    );
const absl::StatusOr<bool> is_convex =
    InvokeRemote(*client, IsConvex(), triangle);
std::cout << *is_convex << "\\n";  // true`,

  kotlin: `import build.skir.service.ServiceClient
// Import from file generated by Skir
import skirout.shapes.IsConvex
import skirout.shapes.Point
import skirout.shapes.Shape

// Construct an immutable Shape
val triangle = Shape(
    points = listOf(
        Point(x = 0, y = 0, label = "A"),
        Point(x = 10, y = 0, label = "B"),
        Point(x = 0, y = 10, label = "C"),
    ),
    label = "ABC",
)

// Demonstrate round-trip serialization
val restored = Shape.serializer.fromJsonCode(
    Shape.serializer.toJsonCode(triangle),
)
println(restored.label)  // ABC

// Send RPC
val isConvex = ServiceClient(
  "http://localhost:8080/api",
).invokeRemote(
    IsConvex,
    triangle,
)

println(isConvex)  // true`,

  java: `import java.time.Duration;
import java.util.List;
import java.util.Map;

import build.skir.service.ServiceClient;
// Import from package generated by Skir
import skirout.shapes.Methods;
import skirout.shapes.Point;
import skirout.shapes.Shape;

// Construct an immutable Shape
final Shape triangle =
    Shape.builder()
        // The compiler requires all fields to be specified
        // in alphabetical order. You can bypass by calling
        // partialBuilder() instead.
        .setLabel("ABC")
        .setPoints(
            List.of(
                Point.builder()
                    .setLabel("A")
                    .setX(0)
                    .setY(0)
                    .build(),
                Point.builder()
                    .setLabel("B")
                    .setX(10)
                    .setY(0)
                    .build(),
                Point.builder()
                    .setLabel("C")
                    .setX(0)
                    .setY(10)
                    .build(),
            ))
        .build();

// Demonstrate round-trip serialization
final Shape restored =
    Shape.SERIALIZER.fromJsonCode(
        Shape.SERIALIZER.toJsonCode(triangle),
    );
System.out.println(restored.label());  // ABC

// Send RPC
final var isConvex =
  new ServiceClient("http://localhost:8080/api")
    .invokeRemoteBlocking(
        Methods.IS_CONVEX,
        triangle,
        Map.of(),
        Duration.ofSeconds(30),
    );

System.out.println(isConvex);  // true`,

  dart: `import 'package:skir_client/skir_client.dart' as skir;
// Import from library generated by Skir
import 'package:your_project/skirout/shapes.dart';

// Construct an immutable Shape
final triangle = Shape(
  points: [
    Point(x: 0, y: 0, label: "A"),
    Point(x: 10, y: 0, label: "B"),
    Point(x: 0, y: 10, label: "C"),
  ],
  label: "ABC",
);

// Demonstrate round-trip serialization
final restored = Shape.serializer.fromJsonCode(
  Shape.serializer.toJsonCode(triangle),
);
print(restored.label); // ABC

// Send RPC
final isConvex = await skir.ServiceClient(
    'http://localhost:8080/api',
)
    .wrap(isConvexMethod)
    .invoke(triangle);

print(isConvex); // true`,

  swift: `import Foundation
import MyLib
import SkirClient

// Construct an immutable Shape
let triangle = Shapes_skir.Shape(
  points: [
    Shapes_skir.Point(x: 0, y: 0, label: "A"),
    Shapes_skir.Point(x: 10, y: 0, label: "B"),
    Shapes_skir.Point(x: 0, y: 10, label: "C"),
  ],
  label: "ABC"
)

// Demonstrate round-trip serialization
let restored = try! Shapes_skir.Shape.serializer.fromJson(
  Shapes_skir.Shape.serializer.toJson(triangle)
)
print(restored.label)  // ABC

// Send RPC
let isConvex = try await SkirClient.ServiceClient(
  serviceUrl: "http://localhost:8080/api"
).invokeRemote(
  Shapes_skir.IsConvex,
  request: triangle
)

print(isConvex)  // true`,

  rust: `use skir_client::ServiceClient;
use skir_client::{JsonFlavor, UnrecognizedValues};
// Import from crate generated by Skir
use skirout::shapes::{is_convex, Point, Shape};

// Construct an immutable Shape
let triangle = Shape {
    label: "ABC".to_string(),
    points: vec![
        Point {
            x: 0,
            y: 0,
            label: "A".to_string(),
            _unrecognized: None,  // Always set to None
        },
        Point {
            x: 10,
            y: 0,
            label: "B".to_string(),
            _unrecognized: None,
        },
        Point {
            x: 0,
            y: 10,
            label: "C".to_string(),
            _unrecognized: None,
        },
    ],
    _unrecognized: None,
};

// Demonstrate round-trip serialization
let restored = Shape::serializer()
    .from_json(
        &Shape::serializer().to_json(
            &triangle,
            JsonFlavor::Dense,
        ),
        UnrecognizedValues::Drop,
    )
    .unwrap();
println!("{}", restored.label); // ABC

// Send RPC
let is_convex = ServiceClient::new(
    "http://localhost:8080/api",
)
    .unwrap()
    .invoke_remote(is_convex(), &triangle, &[])
    .unwrap();

println!("{}", is_convex); // true`,

  go: `import (
    "context"
    "fmt"

    skir "github.com/gepheum/skir-go-client"
    // Import from package generated by Skir
    shapes "github.com/my-org/my-project/skirout/shapes"
)

// Construct an immutable Shape
triangle := shapes.Shape_builder().
    // The compiler requires all fields to be specified
    // in alphabetical order. You can bypass by calling
    // _partialBuilder() instead.
    SetLabel("ABC").
    SetPoints([]shapes.Point{
        shapes.Point_builder().
            SetLabel("A").
            SetX(0).
            SetY(0).
            Build(),
        shapes.Point_builder().
            SetLabel("B").
            SetX(10).
            SetY(0).
            Build(),
        shapes.Point_builder().
            SetLabel("C").
            SetX(0).
            SetY(10).
            Build(),
    }).
    Build()

// Demonstrate round-trip serialization
restored, _ := shapes.Shape_serializer().FromJson(
    shapes.Shape_serializer().ToJson(triangle),
)
fmt.Println(restored.Label()) // ABC

// Send RPC
client := skir.NewServiceClient(
    "http://localhost:8080/api",
)
defer client.Close()

isConvex, err := skir.InvokeRemote(
    context.Background(),
    client,
    shapes.IsConvex(),
    triangle,
)
if err != nil {
    panic(err)
}

fmt.Println(isConvex) // true`,
}

export function CodeExample() {
  return <SplitCodeExample skirCode={skirCode} codeExamples={codeExamples} />
}
