'use client'

import { cn } from '@/lib/utils'
import { useState } from 'react'
// Use Light build to allow custom language registration
import { skirLanguage } from '@/lib/skir-language'
import { Light as SyntaxHighlighter } from 'react-syntax-highlighter'
import python from 'react-syntax-highlighter/dist/esm/languages/hljs/python'
import typescript from 'react-syntax-highlighter/dist/esm/languages/hljs/typescript'
import { atomOneDark } from 'react-syntax-highlighter/dist/esm/styles/hljs'

// Register languages
SyntaxHighlighter.registerLanguage('skir', skirLanguage)
SyntaxHighlighter.registerLanguage('typescript', typescript)
SyntaxHighlighter.registerLanguage('python', python)

const tabs = [
  { id: 'typescript', label: 'TypeScript' },
  { id: 'python', label: 'Python' },
  { id: 'cpp', label: 'C++' },
  { id: 'kotlin', label: 'Kotlin' },
  { id: 'java', label: 'Java' },
  { id: 'dart', label: 'Dart' },
]

const codeExamples = {
  skir: `// shapes.skir

struct Point {
  x: int32;
  y: int32;
  label: string;
}

struct Shape {
  points: [Point];
  /// A short string describing this shape.
  label: string;
}

const TOP_RIGHT_CORNER: Point = {
  x = 600,
  y = 400,
  label = "top-right corner",
};

/// Returns true if no part of the shape's boundary curves inward.
method IsConvex(Shape): bool = 12345;`,

  typescript: `// Import the module generated by Skir
import { Point } from "./skirout/shapes";

// Construct a frozen (immutable) Point
const point = Point.create({
  x: 3,
  y: 4,
  label: "P"
});

// Serialize to dense JSON: compact and allows schema evolution
const pointJson = Point.serializer.toJson(point);
console.log(pointJson);  // [3, 4, "P"]

// Deserialize from JSON
const restored = Point.serializer.fromJson(pointJson);
console.log(restored.label);  // "P"`,

  python: `# Import the module generated by Skir
from skirout.shapes_skir import Point

# Construct a frozen (immutable) Point
point = Point(
    x=3,
    y=4,
    label="P",
)

# Serialize to dense JSON: compact and allows schema evolution
point_json = Point.serializer.to_json_code(point)
print(point_json)  # [3,4,"P"]

# Deserialize from JSON
restored = Point.serializer.from_json_code(point_json)
print(restored.label)  # P`,

  cpp: `// Include the generated header
#include "skirout/shapes.h"

using ::skirout_shapes::Point;

// Construct a Point
Point point = Point::whole{
    .label = "P",
    .x = 3,
    .y = 4,
};

// Serialize to dense JSON: compact and allows schema evolution
std::string point_json = skir::ToDenseJson(point);
std::cout << point_json << "\\n";  // [3,4,"P"]

// Deserialize from JSON
absl::StatusOr<Point> restored = skir::Parse<Point>(point_json);
std::cout << restored->label << "\\n";  // P`,

  kotlin: `// Import generated classes
import skirout.shapes.Point

// Construct a frozen (immutable) Point
val point = Point(
    x = 3,
    y = 4,
    label = "P",
)

// Serialize to dense JSON: compact and allows schema evolution
val pointJson = Point.serializer.toJsonCode(point)
println(pointJson)  // [3,4,"P"]

// Deserialize from JSON
val restored = Point.serializer.fromJsonCode(pointJson)
println(restored.label)  // P`,

  java: `// Import generated classes
import skirout.shapes.Point;

// Construct a frozen (immutable) Point
final Point point =
    Point.builder()
        .setLabel("P")
        .setX(3)
        .setY(4)
        .build();

// Serialize to dense JSON: compact and allows schema evolution
final String pointJson = Point.SERIALIZER.toJsonCode(point);
System.out.println(pointJson);  // [3,4,"P"]

// Deserialize from JSON
final Point restored = Point.SERIALIZER.fromJsonCode(pointJson);
System.out.println(restored.label());  // P`,

  dart: `// Import the generated library
import 'package:your_project/skirout/shapes.dart';

// Construct a frozen (immutable) Point
final point = Point(
  x: 3,
  y: 4,
  label: "P",
);

// Serialize to dense JSON: compact and allows schema evolution
final String pointJson = Point.serializer.toJsonCode(point);
print(pointJson);  // [3,4,"P"]

// Deserialize from JSON
final restored = Point.serializer.fromJsonCode(pointJson);
print(restored.label);  // P`,
}

export function CodeExample() {
  const [activeTab, setActiveTab] = useState('typescript')

  return (
    <div className="rounded-lg border border-border overflow-hidden bg-card">
      {/* Split layout */}
      <div className="flex h-[600px]">
        {/* Left side - Skir code (always visible) */}
        <div className="w-1/2 border-r border-border flex flex-col">
          <div className="px-4 py-3 text-sm font-medium border-b border-border bg-secondary/30 text-primary">
            .skir
          </div>
          <div className="overflow-x-auto overflow-y-auto flex-1">
            <SyntaxHighlighter
              language="skir"
              style={atomOneDark}
              customStyle={{
                margin: 0,
                borderRadius: 0,
                background: 'transparent',
                height: '100%',
              }}
              codeTagProps={{
                style: {
                  fontSize: '0.875rem',
                  fontFamily:
                    'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
                },
              }}
            >
              {codeExamples.skir}
            </SyntaxHighlighter>
          </div>
        </div>

        {/* Right side - Generated code with tabs */}
        <div className="w-1/2 flex flex-col">
          {/* Tabs */}
          <div className="flex border-b border-border bg-secondary/30">
            {tabs.map((tab) => (
              <button
                type="button"
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={cn(
                  'px-4 py-3 text-sm font-medium transition-colors',
                  activeTab === tab.id
                    ? 'text-primary border-b-2 border-primary bg-card'
                    : 'text-muted-foreground hover:text-foreground',
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* Code content */}
          <div className="overflow-x-auto overflow-y-auto flex-1">
            <SyntaxHighlighter
              language={activeTab}
              style={atomOneDark}
              customStyle={{
                margin: 0,
                borderRadius: 0,
                background: 'transparent',
                height: '100%',
              }}
              codeTagProps={{
                style: {
                  fontSize: '0.875rem',
                  fontFamily:
                    'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
                },
              }}
            >
              {codeExamples[activeTab as keyof typeof codeExamples]}
            </SyntaxHighlighter>
          </div>
        </div>
      </div>
    </div>
  )
}
