import { SplitCodeExample } from '@/components/split-code-example'

const skirCode = `// shapes.skir

struct Shape {
  points: [Point];
  /// A short string describing this shape.
  label: string;
}

struct Point {
  x: int32;
  y: int32;
  label: string;
}

method IsConvex(
  Shape
): bool = 412938;`

const codeExamples = {
  typescript: `import { ServiceClient } from "skir-client";
// Import from file generated by Skir
import { IsConvex, Shape } from "../skirout/shapes.js";

// Construct an immutable Shape
const triangle = Shape.create({
  points: [
    { x: 0, y: 0, label: "A" },
    { x: 10, y: 0, label: "B" },
    { x: 0, y: 10, label: "C" },
  ],
  label: "ABC",
});

// Demonstrate round-trip serialization
const restored = Shape.serializer.fromJson(
  Shape.serializer.toJson(triangle)
);

console.log(restored.label);  // ABC

// Send RPC
const isConvex = await new ServiceClient(
  "http://localhost:8080/api"
).invokeRemote(IsConvex, triangle);

console.log(isConvex);  // true`,

  python: `# Import from module generated by Skir
from skirout.shapes_skir import IsConvex, Point, Shape
import skir

# Construct an immutable Shape
triangle = Shape(
    points=(
        Point(x=0, y=0, label="A"),
        Point(x=10, y=0, label="B"),
        Point(x=0, y=10, label="C"),
    ),
    label="ABC",
)

# Demonstrate round-trip serialization
restored = Shape.serializer.from_json_code(
    Shape.serializer.to_json_code(triangle),
)
print(restored.label)  # ABC

# Send RPC
is_convex = skir.ServiceClient(
  "http://localhost:8080/api",
).invoke_remote(
    IsConvex,
    triangle,
)
print(is_convex)  # true`,

  cpp: `#include "httplib.h"
#include "skir.h"
// Import from header generated by Skir
#include "skirout/shapes.h"

using ::skirout_shapes::IsConvex;
using ::skirout_shapes::Point;
using ::skirout_shapes::Shape;

// Construct an immutable Shape
const Shape triangle = Shape::whole{
    .label = "ABC",
    .points = {
        Point::whole{.label = "A", .x = 0, .y = 0},
        Point::whole{.label = "B", .x = 10, .y = 0},
        Point::whole{.label = "C", .x = 0, .y = 10},
    },
};

// Demonstrate round-trip serialization
const absl::StatusOr<Shape> restored =
    skir::Parse<Shape>(skir::ToDenseJson(triangle));
std::cout << restored->label << "\\n";  // ABC

// Send RPC
std::unique_ptr<skir::service::Client> client =
    skir::service::MakeHttplibClient(
        std::make_unique<httplib::Client>(
            "localhost",
            8080,
        ),
        "/api",
    );
const absl::StatusOr<bool> is_convex =
    InvokeRemote(*client, IsConvex(), triangle);
std::cout << *is_convex << "\\n";  // true`,

  kotlin: `import build.skir.service.ServiceClient
// Import from file generated by Skir
import skirout.shapes.IsConvex
import skirout.shapes.Point
import skirout.shapes.Shape

// Construct an immutable Shape
val triangle = Shape(
    points = listOf(
        Point(x = 0, y = 0, label = "A"),
        Point(x = 10, y = 0, label = "B"),
        Point(x = 0, y = 10, label = "C"),
    ),
    label = "ABC",
)

// Demonstrate round-trip serialization
val restored = Shape.serializer.fromJsonCode(
    Shape.serializer.toJsonCode(triangle),
)
println(restored.label)  // ABC

// Send RPC
val isConvex = ServiceClient(
  "http://localhost:8080/api",
).invokeRemote(
    IsConvex,
    triangle,
)

println(isConvex)  // true`,

  java: `import java.time.Duration;
import java.util.List;
import java.util.Map;

import build.skir.service.ServiceClient;
// Import from package generated by Skir
import skirout.shapes.Methods;
import skirout.shapes.Point;
import skirout.shapes.Shape;

// Construct an immutable Shape
final Shape triangle =
    Shape.builder()
        // The compiler requires all fields to be specified
        // in alphabetical order. You can bypass by calling
        // partialBuilder() instead.
        .setLabel("ABC")
        .setPoints(
            List.of(
                Point.builder()
                    .setLabel("A")
                    .setX(0)
                    .setY(0)
                    .build(),
                Point.builder()
                    .setLabel("B")
                    .setX(10)
                    .setY(0)
                    .build(),
                Point.builder()
                    .setLabel("C")
                    .setX(0)
                    .setY(10)
                    .build(),
            ))
        .build();

// Demonstrate round-trip serialization
final Shape restored =
    Shape.SERIALIZER.fromJsonCode(
        Shape.SERIALIZER.toJsonCode(triangle),
    );
System.out.println(restored.label());  // ABC

// Send RPC
final var isConvex =
  new ServiceClient("http://localhost:8080/api")
    .invokeRemoteBlocking(
        Methods.IS_CONVEX,
        triangle,
        Map.of(),
        Duration.ofSeconds(30),
    );

System.out.println(isConvex);  // true`,

  dart: `import 'package:skir_client/skir_client.dart' as skir;
// Import from library generated by Skir
import 'package:your_project/skirout/shapes.dart';

// Construct an immutable Shape
final triangle = Shape(
  points: [
    Point(x: 0, y: 0, label: "A"),
    Point(x: 10, y: 0, label: "B"),
    Point(x: 0, y: 10, label: "C"),
  ],
  label: "ABC",
);

// Demonstrate round-trip serialization
final restored = Shape.serializer.fromJsonCode(
  Shape.serializer.toJsonCode(triangle),
);
print(restored.label); // ABC

// Send RPC
final isConvex = await skir.ServiceClient(
    'http://localhost:8080/api',
)
    .wrap(isConvexMethod)
    .invoke(triangle);

print(isConvex); // true`,

  swift: `import Foundation
import MyLib
import SkirClient

// Construct an immutable Shape
let triangle = Shapes_skir.Shape(
  points: [
    Shapes_skir.Point(x: 0, y: 0, label: "A"),
    Shapes_skir.Point(x: 10, y: 0, label: "B"),
    Shapes_skir.Point(x: 0, y: 10, label: "C"),
  ],
  label: "ABC"
)

// Demonstrate round-trip serialization
let restored = try! Shapes_skir.Shape.serializer.fromJson(
  Shapes_skir.Shape.serializer.toJson(triangle)
)
print(restored.label)  // ABC

// Send RPC
let isConvex = try await SkirClient.ServiceClient(
  serviceUrl: "http://localhost:8080/api"
).invokeRemote(
  Shapes_skir.IsConvex,
  request: triangle
)

print(isConvex)  // true`,

  rust: `use skir_client::ServiceClient;
use skir_client::{JsonFlavor, UnrecognizedValues};
// Import from crate generated by Skir
use skirout::shapes::{is_convex, Point, Shape};

// Construct an immutable Shape
let triangle = Shape {
    label: "ABC".to_string(),
    points: vec![
        Point {
            x: 0,
            y: 0,
            label: "A".to_string(),
            _unrecognized: None,  // Always set to None
        },
        Point {
            x: 10,
            y: 0,
            label: "B".to_string(),
            _unrecognized: None,
        },
        Point {
            x: 0,
            y: 10,
            label: "C".to_string(),
            _unrecognized: None,
        },
    ],
    _unrecognized: None,
};

// Demonstrate round-trip serialization
let restored = Shape::serializer()
    .from_json(
        &Shape::serializer().to_json(
            &triangle,
            JsonFlavor::Dense,
        ),
        UnrecognizedValues::Drop,
    )
    .unwrap();
println!("{}", restored.label); // ABC

// Send RPC
let is_convex = ServiceClient::new(
    "http://localhost:8080/api",
)
    .unwrap()
    .invoke_remote(is_convex(), &triangle, &[])
    .unwrap();

println!("{}", is_convex); // true`,

  go: `import (
    "context"
    "fmt"

    skir "github.com/gepheum/skir-go-client"
    // Import from package generated by Skir
    shapes "github.com/my-org/my-project/skirout/shapes"
)

// Construct an immutable Shape
triangle := shapes.Shape_builder().
    // The compiler requires all fields to be specified
    // in alphabetical order. You can bypass by calling
    // _partialBuilder() instead.
    SetLabel("ABC").
    SetPoints([]shapes.Point{
        shapes.Point_builder().
            SetLabel("A").
            SetX(0).
            SetY(0).
            Build(),
        shapes.Point_builder().
            SetLabel("B").
            SetX(10).
            SetY(0).
            Build(),
        shapes.Point_builder().
            SetLabel("C").
            SetX(0).
            SetY(10).
            Build(),
    }).
    Build()

// Demonstrate round-trip serialization
restored, _ := shapes.Shape_serializer().FromJson(
    shapes.Shape_serializer().ToJson(triangle),
)
fmt.Println(restored.Label()) // ABC

// Send RPC
client := skir.NewServiceClient(
    "http://localhost:8080/api",
)
defer client.Close()

isConvex, err := skir.InvokeRemote(
    context.Background(),
    client,
    shapes.IsConvex(),
    triangle,
)
if err != nil {
    panic(err)
}

fmt.Println(isConvex) // true`,

  zig: `const std = @import("std");
const skir = @import("skir_client.zig");
// Import from file generated by Skir
const shapes_mod = @import("skirout/shapes.zig");

var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
defer arena.deinit();
const allocator = arena.allocator();

// Construct a Shape value
const triangle = shapes_mod.Shape{
    .points = &.{
        .{ .x = 0, .y = 0, .label = "A", ._unrecognized = null },
        .{ .x = 10, .y = 0, .label = "B", ._unrecognized = null },
        .{ .x = 0, .y = 10, .label = "C", ._unrecognized = null },
    },
    .label = "ABC",
    ._unrecognized = null,
};

// Demonstrate round-trip serialization
const serializer = shapes_mod.Shape.serializer();
const dense_json = try serializer.serialize(
    allocator,
    triangle,
    .{ .format = .denseJson },
);
const restored = try serializer.deserialize(
    allocator,
    dense_json,
    .{},
);
std.debug.print("{s}\\n", .{restored.label}); // ABC

// Send RPC
var client = try skir.ServiceClient.init(
    allocator,
    "http://localhost:8080/api",
);
const is_convex = try client.invokeRemote(
    allocator,
    shapes_mod.is_convex_method(),
    triangle,
);
switch (is_convex) {
  .ok => |value| std.debug.print("{}\\n", .{value}), // true
  else => std.debug.print("RPC failed\\n", .{}),
}`,

  gleam: `import gleam/bool
import gleam/httpc
import gleam/io
import skir_client
import skir_client/service_client
import skirout/shapes

// Construct an immutable Shape
let triangle =
  shapes.shape_new(
    "ABC",
    [
      shapes.point_new("A", 0, 0),
      shapes.point_new("B", 10, 0),
      shapes.point_new("C", 0, 10),
    ],
  )

// Demonstrate round-trip serialization
let serializer = shapes.shape_serializer()
let triangle_json = skir_client.to_dense_json_code(serializer, triangle)
let assert Ok(restored) = skir_client.from_json_code(serializer, triangle_json)
io.println(restored.label) // ABC

// Send RPC
let assert Ok(client) =
  service_client.new("http://localhost:8080/api", httpc.send)
let assert Ok(is_convex) =
  service_client.invoke_remote(client, shapes.is_convex_method(), triangle)
io.println(bool.to_string(is_convex)) // True`,
}

const tabs = [
  { id: 'typescript', label: 'TypeScript' },
  { id: 'python', label: 'Python' },
  { id: 'java', label: 'Java' },
  { id: 'cpp', label: 'C++' },
  { id: 'go', label: 'Go' },
  { id: 'kotlin', label: 'Kotlin' },
  { id: 'dart', label: 'Dart' },
  { id: 'swift', label: 'Swift' },
  { id: 'rust', label: 'Rust' },
  { id: 'zig', label: 'Zig' },
  { id: 'gleam', label: 'Gleam', language: 'swift' },
]

export function CodeExample() {
  return <SplitCodeExample skirCode={skirCode} codeExamples={codeExamples} tabs={tabs} />
}
